namespace BigChungus.Unmanaged;

public enum BUTTON_IMAGELIST_ALIGN : uint
{
    BUTTON_IMAGELIST_ALIGN_LEFT = 0,
    BUTTON_IMAGELIST_ALIGN_RIGHT = 1,
    BUTTON_IMAGELIST_ALIGN_TOP = 2,
    BUTTON_IMAGELIST_ALIGN_BOTTOM = 3,
    BUTTON_IMAGELIST_ALIGN_CENTER = 4,
}