namespace BigChungus.Unmanaged;

public enum BUTTON_IMAGELIST_ALIGN : uint
{
    BUTTON_IMAGELIST_ALIGN_LEFT,
    BUTTON_IMAGELIST_ALIGN_RIGHT,
    BUTTON_IMAGELIST_ALIGN_TOP,
    BUTTON_IMAGELIST_ALIGN_BOTTOM,
    BUTTON_IMAGELIST_ALIGN_CENTER,
}