namespace BigChungus.Unmanaged;

public enum SHOW_WINDOW_CMD : uint
{
    SW_HIDE = 0U,
    SW_SHOWNORMAL = 1U,
    SW_NORMAL = 1U,
    SW_SHOWMINIMIZED = 2U,
    SW_SHOWMAXIMIZED = 3U,
    SW_MAXIMIZE = 3U,
    SW_SHOWNOACTIVATE = 4U,
    SW_SHOW = 5U,
    SW_MINIMIZE = 6U,
    SW_SHOWMINNOACTIVE = 7U,
    SW_SHOWNA = 8U,
    SW_RESTORE = 9U,
    SW_SHOWDEFAULT = 10U,
    SW_FORCEMINIMIZE = 11U,
    SW_MAX = 11U,
}
